### PR TITLE
Fix bug

### LINKED ISSUE #618: Choose Background File Crash
**Cause**  
Steps to reproduce the crash:  
1.  Launch Hyperium **in fullscreen mode**
2.  Press "Change Menu Background"
3.  Click "Choose File"

**Desktop (please complete the following information):**  
 - OS: [Windows 10 Home x64]  
 - Version: [Hyperium 1.0.2 2179]  

**Additional context**
  
It's freezing, because "choose file" popup is displayed under the minecraft window. User can't see the popup, and clicking on anything in minecraft makes the game crash.

### PR DESCRIPTION
**Pull request by RDIL**
## Description  
Fixes a bug with the background options screen.  

## Context  
Fixes #618 

## Anything Else  
@CoalCoding

### CODE REVIEW

**Comment by RDIL** [comment]
Ill add a check if its in fullscreen later

File: src/main/java/cc/hyperium/gui/ChangeBackgroundGui.java [hunk 1]
```diff
@@ -28,7 +44,7 @@
 public class ChangeBackgroundGui extends GuiScreen {
 
     private final GuiScreen prevGui;
-
+    private static final boolean isFS = Minecraft.getMinecraft().isFullScreen();
```
Comment (CoalCoding) [inline src/main/java/cc/hyperium/gui/ChangeBackgroundGui.java]: This shouldn't be static or final. The user can change whether they're on fullscreen mode while the GUI is open. Instead, call Minecraft.getMinecraft().isFullScreen() in each of the methods where this is used, or assign it to a variable within the methods where it is used multiple times.

File: src/main/java/cc/hyperium/gui/ChangeBackgroundGui.java [hunk 2]
```diff
@@ -55,23 +74,35 @@ public void updateScreen() {
     @Override
     protected void keyTyped(char typedChar, int keyCode) throws IOException {
         this.downloadUrlField.textboxKeyTyped(typedChar, keyCode);
-        if (keyCode == Keyboard.KEY_ESCAPE)
+        if (keyCode == Keyboard.KEY_ESCAPE) {
             Minecraft.getMinecraft().displayGuiScreen(this.prevGui);
-        if (keyCode == Keyboard.KEY_RETURN)
+            if(isFS) {
+                Minecraft.getMinecraft().toggleFullscreen();
+            }
```
Comment (CoalCoding) [inline src/main/java/cc/hyperium/gui/ChangeBackgroundGui.java]: The problem I mentioned earlier is apparent here, if you press "escape" multiple times it will switch between fullscreen and windowed mode since the value of isFS never updates.

File: src/main/java/cc/hyperium/gui/ChangeBackgroundGui.java (hunk 1 above)
Comment (RDIL) [reply src/main/java/cc/hyperium/gui/ChangeBackgroundGui.java]: 👍

**Comment by RDIL** [comment]
Fixed

File: src/main/java/cc/hyperium/gui/ChangeBackgroundGui.java [hunk 3]
```diff
@@ -55,23 +73,35 @@ public void updateScreen() {
     @Override
     protected void keyTyped(char typedChar, int keyCode) throws IOException {
         this.downloadUrlField.textboxKeyTyped(typedChar, keyCode);
-        if (keyCode == Keyboard.KEY_ESCAPE)
+        if (keyCode == Keyboard.KEY_ESCAPE) {
             Minecraft.getMinecraft().displayGuiScreen(this.prevGui);
-        if (keyCode == Keyboard.KEY_RETURN)
+            if(isFS) {
```
Comment (CoalCoding) [inline src/main/java/cc/hyperium/gui/ChangeBackgroundGui.java]: This variable no longer exists?

Comment (RDIL) [reply src/main/java/cc/hyperium/gui/ChangeBackgroundGui.java]: well it isn't needed now

Comment (CoalCoding) [reply src/main/java/cc/hyperium/gui/ChangeBackgroundGui.java]: But you are still accessing it, thus causing an error since the variable does not exist.

Comment (RDIL) [reply src/main/java/cc/hyperium/gui/ChangeBackgroundGui.java]: missed that one, my bad

**Comment by RDIL** [comment]
travis be happy so I be happy

**Comment by CoalCoding** [comment]
This is a band-aid fix for now. A solution to open the file selection window in fullscreen would be more ideal.
